#!/usr/bin/env python
"""Regenerate Figure 1 (cohort viewer) multiscale data blocks in ``pi_report.html``.

The cohort figure's detail panel shows each field through three lenses (DNA /
Cells / Lineage) at three analysis grains (10 / 20 / 40 µm superpixels). DNA is
the invariant 1 µm substrate and lives in ``THUMBS_DNA`` (not touched here). This
script regenerates everything that IS scale-dependent, from the frozen pipeline
products, and splices it into the report between sentinel comments so re-running
is idempotent:

  THUMBS_LABEL[scale][key]   discrete cell-type raster  (organic superpixels)
  THUMBS_TERNARY[scale][key] continuous lineage RGB raster
  THUMBS_META[scale][key]    {n_sp, n_assigned} grain readout
  CELL_COLORS / CELL_LABELS  15-type palette + labels (from viz.json — single
  CELL_FAMILIES / CELL_ORDER   source of truth for the Cells legend)
  PATCHES[scale][key]        per-superpixel [x,y,ctIdx,im,st,en,cd44,cd140b]
                             (scores ×100) for the hover popover (nearest-centroid)

Recipe fidelity: the 10 µm Sham reference is READ from the frozen gating anchor
``sham_reference_10.0um.json`` so the 10 µm layer is bit-identical to the rest of
the report; 20/40 µm references are generated by the same frozen recipe
(``generate_sham_reference.generate``) and written next to it as committed
artifacts. Cell-type gating + sham_reference_v2 membership come from the frozen
``annotate_roi_from_results``.

Lineage → RGB channel mapping is immune=R, stromal=G, endothelial=B (matches the
report legend + the original hand-built raster, verified by channel correlation).

Usage:
  python review_packet/make_fig1_multiscale_rasters.py            # regen + splice
  python review_packet/make_fig1_multiscale_rasters.py --rois D7_M2_02   # subset (dev)
  python review_packet/make_fig1_multiscale_rasters.py --no-splice --dump out.json
"""
from __future__ import annotations
import argparse
import base64
import io
import json
import re
import sys
from pathlib import Path

import numpy as np
from PIL import Image

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from src.config import Config                                              # noqa: E402
from src.utils.canonical_loader import load_roi_results, deserialize_array  # noqa: E402
from src.utils.metadata import parse_roi_metadata                          # noqa: E402
from src.analysis.cell_type_annotation import annotate_roi_from_results    # noqa: E402
from batch_annotate_all_rois import deserialize_numpy_arrays               # noqa: E402
import generate_sham_reference as gsr                                      # noqa: E402

REPORT = REPO / 'review_packet' / 'pi_report.html'
BIO = REPO / 'results' / 'biological_analysis'
ROI_DIR = REPO / 'results' / 'roi_results'
SCALES = (10.0, 20.0, 40.0)
RENDER = 360          # match the report's THUMBS_LABEL / THUMBS_TERNARY tile size
PAPER = (250, 248, 243)
LINEAGE_ORDER = ('immune', 'stromal', 'endothelial')  # -> R, G, B

# Lineage family of each discrete type + the family header shown in the legend.
FAMILY_OF = {
    'neutrophil': 'immune', 'immune_cells': 'immune', 'activated_immune': 'immune',
    'myeloid': 'myeloid', 'm2_macrophage': 'myeloid',
    'activated_myeloid_cd44': 'myeloid', 'activated_myeloid_cd140b': 'myeloid',
    'activated_m2_cd44': 'myeloid', 'activated_m2_cd140b': 'myeloid',
    'endothelial': 'endothelial',
    'activated_endothelial_cd44': 'endothelial', 'activated_endothelial_cd140b': 'endothelial',
    'fibroblast': 'stromal',
    'activated_fibroblast_cd44': 'stromal', 'activated_fibroblast_cd140b': 'stromal',
}
FAMILY_META = [
    ('immune', 'Immune', 'CD45⁺'),
    ('myeloid', 'Myeloid', 'CD11b⁺'),
    ('endothelial', 'Endothelial', 'CD31⁺ CD34⁺'),
    ('stromal', 'Stromal', 'CD140a⁺'),
]

SENTINEL_START = '  // <<<FIG1_MULTISCALE_DATA — generated by review_packet/make_fig1_multiscale_rasters.py; do not hand-edit>>>'
SENTINEL_END = '  // <<<END_FIG1_MULTISCALE_DATA>>>'


def hex2rgb(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def load_viz_palette():
    disp = json.load(open(REPO / 'viz.json'))['cell_type_display']
    colors = {k: v['color'] for k, v in disp.items() if isinstance(v, dict) and 'color' in v}
    labels = {k: v.get('label', k) for k, v in disp.items() if isinstance(v, dict) and 'color' in v}
    return colors, labels


def load_reference(scale_um):
    """10 µm: read the frozen gating anchor (bit-identical to the rest of the
    report). 20/40 µm: generate via the frozen recipe + persist next to it."""
    path = BIO / f'sham_reference_{scale_um}um.json'
    if not path.exists():
        if scale_um == 10.0:
            raise FileNotFoundError(f'frozen sham reference missing: {path}')
        print(f'[ref] generating {path.name} (frozen recipe @ {scale_um}µm) ...', flush=True)
        gsr.generate(scale_um=float(scale_um), output_path=path, config_path=REPO / 'config.json')
    ref = json.load(open(path)).get('reference', {})
    return {m: {'threshold': float(v['threshold']), 'scale': float(v['scale'])}
            for m, v in ref.items() if isinstance(v, dict) and 'threshold' in v}


def deser(x):
    try:
        return deserialize_array(x)
    except Exception:
        return np.asarray(x)


def label_to_row_lut(seg):
    """SLIC label ids are non-contiguous (gaps, -1 = background); annotation rows
    are compacted 0..N-1 in ascending-label order. Return (LUT, N)."""
    pos = np.unique(seg)
    pos = pos[pos >= 0]
    lut = np.full(int(seg.max()) + 1, -1, dtype=np.int64)
    lut[pos] = np.arange(len(pos))
    return lut, len(pos)


def paint_from_labels(seg, per_sp_rgba):
    """seg (H,W) label ids -> RGBA image, coloring each superpixel by its row."""
    H, W = seg.shape
    lut, n = label_to_row_lut(seg)
    assert per_sp_rgba.shape[0] == n, f'{per_sp_rgba.shape[0]} rows != {n} superpixels'
    flat = seg.ravel().astype(np.int64)
    rows = np.where(flat >= 0, lut[np.clip(flat, 0, lut.size - 1)], -1)
    valid = rows >= 0
    out = np.zeros((H * W, 4), dtype=np.uint8)
    out[valid] = per_sp_rgba[rows[valid]]
    im = Image.fromarray(out.reshape(H, W, 4))
    if (H, W) != (RENDER, RENDER):
        im = im.resize((RENDER, RENDER), Image.NEAREST)
    return im


def celltype_rgba(cell_types, colors_rgb):
    """Opaque type color per assigned superpixel; unassigned -> transparent so the
    DNA substrate shows through."""
    rgba = np.zeros((len(cell_types), 4), np.uint8)
    for i, ct in enumerate(cell_types):
        if ct in colors_rgb:
            rgba[i] = (*colors_rgb[ct], 255)
    return rgba


def lineage_rgba(lin_scores, gamma=0.7):
    """Lineage RGB (R=immune, G=stromal, B=endothelial) with signal-proportional
    alpha over paper: strong lineage vivid, weak pastel, none transparent. Dual /
    triple lineages keep their blends (yellow / cyan / magenta / near-white)."""
    N = len(next(iter(lin_scores.values())))
    rgb = np.zeros((N, 3))
    for i, ln in enumerate(LINEAGE_ORDER):
        if ln in lin_scores:
            rgb[:, i] = np.clip(np.asarray(lin_scores[ln], float), 0, 1)
    row_max = rgb.max(axis=1)
    cur = row_max.copy()
    cur[cur == 0] = 1.0
    hue = np.clip(rgb / cur[:, None], 0, 1)
    alpha = np.clip(row_max, 0, 1) ** gamma
    return np.concatenate([(hue * 255).astype(np.uint8),
                           (alpha * 255).astype(np.uint8)[:, None]], axis=1)


def png_b64(im):
    buf = io.BytesIO()
    im.save(buf, 'PNG', optimize=True)
    return 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode()


def encode_ternary(im, colors=64):
    """Flatten lineage pastel over paper + adaptive-palette quantize (~1/3 the size
    of smooth RGBA, visually identical at tile scale)."""
    bg = Image.new('RGBA', im.size, PAPER + (255,))
    flat = Image.alpha_composite(bg, im).convert('RGB')
    return png_b64(flat.quantize(colors=colors, method=Image.FASTOCTREE))


def report_key(roi_id):
    """roi_IMC_..._D7_M2_02_25 -> 'D7/MS2/02_25' (matches ROIS keys in the report)."""
    meta = parse_roi_metadata(roi_id)
    m = re.search(r'_(\d+)_(\d+)$', roi_id)
    idx, raw = int(m.group(1)), m.group(2)
    return f"{meta['timepoint']}/{meta['mouse']}/{idx:02d}_{raw}"


def q100(a):
    return [int(round(float(v) * 100)) for v in a]


def build_payload(scales, roi_filter):
    config = Config(str(REPO / 'config.json'))
    colors_hex, labels = load_viz_palette()
    colors_rgb = {k: hex2rgb(v) for k, v in colors_hex.items()}
    ct_order = list(config.raw['cell_type_annotation']['cell_types'].keys()) + ['unassigned']
    ct_index = {name: i for i, name in enumerate(ct_order)}

    refs = {sc: load_reference(sc) for sc in scales}

    roi_files = sorted(ROI_DIR.glob('roi_*_results.json.gz'))
    if roi_filter:
        subs = roi_filter.split(',')
        roi_files = [f for f in roi_files if any(s in f.name for s in subs)]

    payload = {k: {str(sc): {} for sc in scales} for k in ('LABEL', 'TERNARY', 'META', 'PATCHES')}

    for rf in roi_files:
        roi_id = rf.stem.replace('_results.json', '')
        key = report_key(roi_id)
        results = deserialize_numpy_arrays(load_roi_results(rf))
        for sc in scales:
            skey = str(sc)
            sd = results.get('multiscale_results', {}).get(skey)
            if sd is None:
                print(f'  ! {roi_id} missing scale {skey}')
                continue
            seg = deser(sd['superpixel_labels']).astype(np.int64)
            coords = np.asarray(deser(sd['superpixel_coords']))
            ann = annotate_roi_from_results(results, config, scale=skey, reference_distribution=refs[sc])
            cts = np.asarray(ann['cell_type_labels'], dtype=object)
            mem = ann.get('memberships') or {}
            lin = mem.get('lineage_scores', {})
            act = mem.get('activation_scores', {})

            payload['LABEL'][skey][key] = png_b64(paint_from_labels(seg, celltype_rgba(cts, colors_rgb)))
            if lin:
                payload['TERNARY'][skey][key] = encode_ternary(paint_from_labels(seg, lineage_rgba(lin)))
            payload['META'][skey][key] = {'n_sp': int(len(cts)), 'n_assigned': int(np.sum(cts != 'unassigned'))}

            im100 = q100(lin.get('immune', np.zeros(len(cts))))
            st100 = q100(lin.get('stromal', np.zeros(len(cts))))
            en100 = q100(lin.get('endothelial', np.zeros(len(cts))))
            c44 = q100(act.get('cd44', np.zeros(len(cts))))
            c140 = q100(act.get('cd140b', np.zeros(len(cts))))
            rows = [[int(round(coords[i, 0])), int(round(coords[i, 1])),
                     ct_index.get(cts[i], len(ct_order) - 1),
                     im100[i], st100[i], en100[i], c44[i], c140[i]] for i in range(len(cts))]
            payload['PATCHES'][skey][key] = rows
            print(f'  {roi_id} @ {skey}: {len(cts)} sp, {int(np.sum(cts != "unassigned"))} assigned', flush=True)

    families = [{'family': fam, 'label': lab, 'marker': mk,
                 'types': _family_types(fam, ct_order)} for fam, lab, mk in FAMILY_META]
    palette = {
        'CELL_COLORS': colors_hex,
        'CELL_LABELS': labels,
        'CELL_ORDER': ct_order,
        'CELL_FAMILIES': families,
    }
    return payload, palette


# Canonical/headline base type to lead each family in the legend (neutrophil is
# the report's headline cell type; the others are the generic lineage base).
PRIMARY_BASE = {'neutrophil', 'myeloid', 'endothelial', 'fibroblast'}


def _family_types(fam, ct_order):
    members = [t for t in ct_order if FAMILY_OF.get(t) == fam]
    # canonical base first, then remaining base types, then activated variants
    members.sort(key=lambda t: (t.startswith('activated_'), t not in PRIMARY_BASE, t))
    return members


def const_line(name, obj):
    return f'  const {name} = ' + json.dumps(obj, separators=(',', ':')) + ';'


def splice(html, payload, palette):
    region = '\n'.join([
        SENTINEL_START,
        const_line('THUMBS_LABEL', payload['LABEL']),
        const_line('THUMBS_TERNARY', payload['TERNARY']),
        const_line('THUMBS_META', payload['META']),
        const_line('PATCHES', payload['PATCHES']),
        const_line('CELL_COLORS', palette['CELL_COLORS']),
        const_line('CELL_LABELS', palette['CELL_LABELS']),
        const_line('CELL_ORDER', palette['CELL_ORDER']),
        const_line('CELL_FAMILIES', palette['CELL_FAMILIES']),
        SENTINEL_END,
    ])
    if SENTINEL_START in html:
        i = html.index(SENTINEL_START)
        j = html.index('\n', html.index(SENTINEL_END))
        return html[:i] + region + html[j:]
    # First run: replace the pre-existing THUMBS_LABEL..THUMBS_META span.
    i = html.index('  const THUMBS_LABEL = {')
    end_anchor = '  const THUMBS_META = {' if 'const THUMBS_META = {' in html else '  const THUMBS_TERNARY = {'
    j = html.index('\n  };', html.index(end_anchor)) + len('\n  };')
    return html[:i] + region + html[j:]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--scales', default='10.0,20.0,40.0')
    ap.add_argument('--rois', default='', help='comma substrings to subset ROIs (dev)')
    ap.add_argument('--no-splice', action='store_true', help='do not modify the report')
    ap.add_argument('--dump', default='', help='also write the raw payload JSON here')
    args = ap.parse_args()
    scales = [float(s) for s in args.scales.split(',')]

    payload, palette = build_payload(scales, args.rois)
    if args.dump:
        json.dump({**payload, **palette}, open(args.dump, 'w'))
        print(f'[dump] {args.dump}')

    if not args.no_splice:
        html = REPORT.read_text()
        REPORT.write_text(splice(html, payload, palette))
        size = REPORT.stat().st_size
        print(f'[splice] {REPORT} — {size/1024/1024:.1f} MB')


if __name__ == '__main__':
    main()
