#' Import Processed Single-Cell Data from Steinbock Pipeline
#'
#' This entrypoint imports the processed single-cell data generated by the
#' steinbock pipeline along with the associated multi-channel images and
#' segmentation masks. It leverages our core infrastructure for configuration,
#' dependency management, logging, progress tracking, and results exporting.
#'
#' @return A list containing the SpatialExperiment object (spe),
#'         images and masks objects, and progress summary.
#'
#' @example
#'   data_objects <- runImportSteinbockData()

# Load core classes
source("src/core/ConfigurationManager.R")
source("src/core/DependencyManager.R")
source("src/core/Logger.R")
source("src/core/ProgressTracker.R")
source("src/core/ResultsManager.R")

runImportSteinbockData <- function() {
  # ------------------------ Initialization ------------------------
  # Instantiate logger: log messages to both the console and a logfile.
  logger <- Logger$new(log_file = "logs/importSteinbockData.log", log_level = "INFO")
  
  # Load configuration settings (merging defaults with any user-provided overrides)
  configManager <- ConfigurationManager$new()
  # Optionally merge user settings:
  # configManager$merge_with_defaults(user_config)
  
  # Instantiate and validate dependencies with our logger.
  dependencyManager <- DependencyManager$new(logger = logger)
  dependencyManager$validate_environment()
  
  # Initialize progress tracking and results management.
  progressTracker <- ProgressTracker$new(logger = logger)
  resultsManager <- ResultsManager$new(logger = logger)
  
  progressTracker$start_phase("Import Steinbock Processed Data")
  
  # ------------------------ Phase 1: Read Processed Data ------------------------
  # Import the SpatialExperiment object using the imcRtools package.
  library(imcRtools)
  steinbock_data_path   <- configManager$config$paths$steinbock_data
  steinbock_images_path <- configManager$config$paths$steinbock_images
  steinbock_masks_path  <- configManager$config$paths$steinbock_masks
  
  spe <- read_steinbock(steinbock_data_path)
  logger$log_info("Loaded SpatialExperiment (spe) from steinbock results.")
  
  # ------------------------ Phase 2: Read Images & Masks ------------------------
  # Use cytomapper for multi-channel image and mask handling.
  library(cytomapper)
  images <- loadImages(steinbock_images_path)
  masks  <- loadImages(steinbock_masks_path, as.is = TRUE)
  
  # Ensure channel consistency between the SpatialExperiment and images.
  channelNames(images) <- rownames(spe)
  logger$log_info("Loaded multi-channel images and segmentation masks; channel names updated.")
  
  progressTracker$update_progress(50, "Data import completed for single-cell & image objects")
  
  # ------------------------ Phase 3: Save Imported Data ------------------------
  # Save the imported objects if configured to do so.
  output_dir <- configManager$config$output$dir
  if (isTRUE(configManager$config$output$save_data)) {
    if (!dir.exists(output_dir)) {
      dir.create(output_dir, recursive = TRUE)
    }
    saveRDS(spe, file = file.path(output_dir, "spe.rds"))
    saveRDS(images, file = file.path(output_dir, "images.rds"))
    saveRDS(masks, file = file.path(output_dir, "masks.rds"))
    logger$log_info("Saved spe, images, and masks to output directory: %s", output_dir)
  }
  
  # Store the results via the ResultsManager for downstream uses.
  resultsManager$add_result("spe", spe)
  resultsManager$add_result("images", images)
  resultsManager$add_result("masks", masks)
  
  progressTracker$complete_phase()
  
  # ------------------------ Completion ------------------------
  summaryInfo <- progressTracker$get_summary()
  logger$log_info("Import entrypoint completed in %.2f seconds.", summaryInfo$total_duration)
  
  invisible(list(
    spe    = spe,
    images = images,
    masks  = masks,
    progress_summary = summaryInfo
  ))
}

# Execute the entrypoint when running interactively.
if (interactive() || identical(environment(), globalenv())) {
  data_objects <- runImportSteinbockData()
} 